# Generated by Django 5.2.5 on 2025-08-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_decription_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(choices=[('default', 'Select duration'), ('one week', '1 week'), ('one week', '1 week'), ('one week', '1 week'), ('one week', '1 week')], default='default'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
